### ISSUE TITLE
Correção do nome do diretório do plumber em node_modules

### ISSUE THREAD

**Issue by leobaiano** [fdaciuk/talks#1]
No slide 48 da apresentação "Um gole de otimização no WordPress" (https://docs.google.com/presentation/d/1-J8IomiCFn33wWT_7Ep7hY_2dR-WvFJ2jcYm2RUeSJ0/edit#slide=id.g126141da2_090) está apontando para o nome errado do diretório do plumber no gulpfile.js.

Na apresentação está assim:

var plumber = require( 'gulp-plumber' );

Porém ao adicionar o plumber ao projeto o nome do diretório é apenas "plumber", mantendo gulp-plumber da erro.

**Comment by fdaciuk** [comment]
Opa.. valeu pelo toque @leobaiano! Eu acho que pode ter alguma outra coisa dando esse erro, porque o nome do plugin é esse mesmo: https://www.npmjs.org/package/gulp-plumber

Mas vou verificar.. valeu por avisar! o/

**Comment by fdaciuk** [comment]
Meu.. agora que lembrei dessa task xD
Conferi agora: o nome está correto: é gulp-plumber mesmo. Talvez você não tenha instalado a dependência, ou colocou separado `npm install gulp plumber`, ao invés de usar traço, ae foi instalado o gulp e o plumber :)
